"""migration 2

Revision ID: 44de04ad6eb3
Revises: 5d41a89de862
Create Date: 2022-10-17 00:53:22.999006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44de04ad6eb3'
down_revision = '5d41a89de862'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
