"""migration 1

Revision ID: 5d41a89de862
Revises: c67b8c94c803
Create Date: 2022-10-17 00:51:44.141352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d41a89de862'
down_revision = 'c67b8c94c803'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
